### PR TITLE
Adding just a metric to be sure that the server is up or not

### PR DESCRIPTION
**Pull request by mitraillet**
I found your package really interesting but I found it lacks of proper way to now if the ntp server is up or down. 
So I just add a small "metric" to say it. 
I never programme in go language so I don't now if it's the proper way to do but it's a functionnal one.

### CODE REVIEW

**Comment by majewsky** [comment]
I don't think this is necessary. As it stands right now, when the NTP server is down, we don't send any metrics, so you could detect the downtime with an alert on `absent(ntp_drift_seconds)`.

**Comment by mitraillet** [comment]
Yes but if the exporter for no reason stop or failed you are going to have a wrong alert about it. That's just my point of view.

**Comment by majewsky** [comment]
If the exporter stops for no good reason, I *definitely* want to get an alert, because that indicates that something is seriously wrong with it.

**Comment by mitraillet** [comment]
Yes that's the point with the actual system you cannot know if it's the system or the ntp who've got the issue so by adding a metric you can be more precise. And create two different alerts

**Comment by majewsky** [comment]
I had a final look at this, and I'm convinced that this is not needed. To alert on an unavailable NTP server, use `absent(ntp_drift_seconds)` or similar. To alert on an unavailable ntp_exporter, use `up{job="ntp_exporter"}` or similar. The `up` metric is generated by the Prometheus server itself as it scrapes the exporter, and is therefore more reliable than anything we can emit ourselves.

**Pull request closed without merging**
